services:
  db:
    container_name: db
    image: "postgres:${POSTGRES_VERSION}"
    env_file:
      - ".env"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - backend-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  backend-network:
    driver: bridge